### ISSUE TITLE
Possible Connection Guide error & More in-depth instructions

### ISSUE THREAD

**Issue by rocky517** [Plexis/Plexis#10]
For some reason the Connection Guide always has 127.0.0.1 as the IP.. (Wasn't this fetched from the auth realmlist table?

[quote]
5. Edit your "realmlist.wtf" (C:\Program Files\worldofwarcaft\data\enUS\realmlist.wtf) and change "Set Realmlist us.logon.worldofwarcraft.com" TO "set Realmlist 127.0.0.1"
[/quote]

Also please include further instructions because some users might have enGB clients or x64 systems. (Therefore directories can differ)

**Comment by mitchellholzmann** [comment]
No you can set the realmlist in your realm configuration of the cms.

These pages will soon be able to be changed, so just wait till they finish it.

Issue can be closed, no bug here.
