### ISSUE TITLE
SSL Error after latest rev

### ISSUE THREAD

**Issue by mitchellholzmann** [Plexis/Plexis#16]
After the latest revision, my auto updates gives the error "Open SSL extension not found. Please enable Open SSL in your php.ini file (extension=php_openssl.dll on Windows or extensions=openssl.so on Linux).". It did not give this error before and worked fine.

Seems I'm not the only one with this problem.

**Comment by clarajk** [comment]
That should mean it's working as intended, if Open SSL isn't enabled. If it's erroneously reporting that it's not enabled then we do have a genuine problem.

If you wouldn't mind testing, comment out two of the elseif blocks in `system/controllers/admin.php` starting at line 707 so it looks like this: 

``` php
if( !extension_loaded( "curl" ) )
{
    $Message = "cURL extension not found. Please enable cURL in your php.ini file (extension=php_curl.dll on Windows or extensions=curl.so on Linux).";
    output_message( "warning", $Message );
    $this->load->view( "blank", $data );
    return;
}
/*elseif( !extension_loaded( "openssl" ) )
{
    $Message = "Open SSL extension not found. Please enable Open SSL in your php.ini file (extension=php_openssl.dll on Windows or extensions=openssl.so on Linux).";
    output_message( "warning", $Message );
    $this->load->view( "blank", $data );
    return;
}*/
elseif( ini_get( "allow_url_fopen" ) != 1 )
{
    $Message = "Please enable allow_url_fopen in your php.ini file and try again.";
    output_message( "warning", $Message );
    $this->load->view( "blank", $data );
    return;
}
/*elseif( !in_array( "https", stream_get_wrappers() ) ) //We shouldn't arive here, as Open SSL adds the HTTPS stream wrapper.
{
    $Message = "HTTPS support could not be detected, please allow HTTPS streams and then try again.";
    output_message( "warning", $Message );
    $this->load->view( "blank", $data );
    return;
}*/
```

Then run the remote updater again, if you can successfully update without the need for Open SSL or HTTPS stream wrappers then we can just remove the requirement checking for them entirely.

Also, supplying the extensions section of php.ini, server OS and the value returned by `print_r( get_loaded_extensions(), true );` could also help debunk this.

**Comment by mitchellholzmann** [comment]
Works just fine after commenting out those lines.
