### ISSUE TITLE
Multi Language Support

### ISSUE THREAD

**Issue by mike2011lp** [Plexis/Plexis#21]
Hi, is there any chance to include a multi language support feature in the cms?

I'm not telling you to include the translations texts for all languages, only the support for making it possible.

Then the community could be able to collaborate with this task.

Thanks in advance.

**Comment by clarajk** [comment]
Look closer, Plexis does have multi-language support, in both core language files (used for things such as error message output) and templates, including the ACP template. However, the responsibility for translating the CMS rests solely on the community. Moreover the language system is **incomplete** and likely to change at any time, and it _will_ change some time before Plexis moves to a stable release.

Also please reserve any questions, support requests or feature requests for our [official forums](http://plexis.tk/forum), we have sections just for that. The issue tracker is to be used for reporting bugs or submitting your own code to further the development of the CMS.
