### ISSUE TITLE
Problem with Server Status

### ISSUE THREAD

**Issue by MauryTigre** [Plexis/Plexis#24]
Hi, I have a problem with the detection of the realm.
I tried in every way but nothing. You tell me what to put in the boxes in the table "pcms_realms" SQL? I would be grateful.
I always error and I do not find the Realm.

Maurizio.

**Comment by ChazyTheBest** [comment]
Check the required config for PHP: http://plexis.tk/forum/showthread.php?tid=15

**Comment by clarajk** [comment]
Use the Realm Management page in the ACP if you need to install a new realm, it supports manually adding realms as well (to support those not contained in the realmlist table in your auth db for whatever reason). The fields inside the pcms_realms table take serialized arrays generated by PHP's [serialize()](http://php.net/manual/en/function.serialize.php) function, Short of writing your own script and running to spit out the proper data it can't be done without the CMS, and it certainly can't be done without PHP.
