### ISSUE TITLE
Percentage of Site Functionality

### ISSUE THREAD

**Issue by FooFKnight** [Plexis/Plexis#3]
Hello, I want to Know What Bugs that have already been found in PlexisWeb for me Stay abreast of Bugs

**Comment by clarajk** [comment]
The issue tracker is not for support, please visit the community forums at [http://wilson212.com/forum](http://wilson212.com/forum) or the official AC Web thread [here](http://www.ac-web.org/forums/showthread.php?t=145528).

**Comment by wazy** [comment]
Looks like wilson212.net is suspended.
