### ISSUE TITLE
mod_rewrite

### ISSUE THREAD

**Issue by clarajk** [Plexis/Plexis#5]
This is just a reminder for myself as well as the other devs: when trying to run Plexis without mod_rewrite enabled on Apache the site will not function at all, causing an infinite redirect loop.

**Comment by Faded** [comment]
Should we have plexis come with a .htaccess with the needed info?

**Comment by clarajk** [comment]
We already have a .htaccess that deals with the rewrite module, Plexis detects whether or not it's enabled and routes the URL accordingly, it's what the system is trying to do with it at that point that's the issue.

Although upon further investigation, I found it's only the automatic redirection to the installer that causes this problem, the site redirects to http://localhost/Plexis/index.php?url=/install/index.php when it should be redirecting to http://localhost/Plexis/install/index.php, each time we get bounced back to index.php the system tries to send us to the installer instead, but only ends up causing the redirect loop.

**Comment by wazy** [comment]
From setting it up I can confirm what is said above. Only redirect comes from accessing installer.
